version: '3.8'

services:
  # Hono API Application
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - HOST=0.0.0.0
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - hono-network

networks:
  hono-network:
    driver: bridge 